apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - image: bitnami/mongodb
    name: main
    volumeMounts:
    - name: mongodb-data
      mountPath: /bitnami/mongodb
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: test-claim1
