apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: web
spec:
   serviceName: "nginx"
   replicas: 2
   selector:
     matchLabels:
       app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
       containers:
       - name: main
         image: quay.io/jitesoft/nginx
         ports:
         - containerPort: 80
           name: web
         volumeMounts:
         - name: www
           mountPath: /usr/share/nginx/html\
       volumes:
       - name: www
         persistentVolumeClaim:
           claimName: test-claim2